name: deep-speaker
channels:
  - defaults
dependencies:
  - ipython=7.19.0
  - isort=5.6.4
  - jupyter=1.0.0
  - keras=2.3.1
  - matplotlib=3.2.1
  - numpy=1.18.5
  - pandas=1.0.3
  - pip=20.3.3
  - pytest=6.2.1
  - python=3.7.9
  - requests=2.25.*
  - scipy=1.5.2
  - sqlite=3.33.0
  - tensorflow=2.1.0
  - pip:
    - audioread==2.1.9
    - joblib==1.0.0
    - librosa
    - python-speech-features==0.6
    - resampy==0.2.2
    - scikit-learn==0.23.2
